version: '3.8'

networks:
  bridge:
    driver: bridge

services:
  db:
    container_name: surgery-solicitation-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'surgery-solicitation'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_CHARACTER_SET_SERVER: utf8
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    # The following line is needed to allow the container to be accessed from outside the host machine (e.g. from a GUI tool like MySQL Workbench). Not meant for production!
    command: --bind-address=0.0.0.0
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql
    networks:
      - bridge
