// REPOSITORIES
export const INJECTION_REPOSITORY_SURGERY_SOLICITATION =
  '@INJECTION_REPOSITORY_SURGERY_SOLICITATION';

//SERVICES
export const INJECTION_SERVICE_CREATE_SURGERY_SOLICITATION =
  '@INJECTION_SERVICE_CREATE_SURGERY_SOLICITATION';
export const INJECTION_SERVICE_UPDATE_SURGERY_SOLICITATION =
  '@INJECTION_SERVICE_UPDATE_SURGERY_SOLICITATION';
export const INJECTION_SERVICE_FIND_ALL_SURGERY_SOLICITATION =
  '@INJECTION_SERVICE_FIND_ALL_SURGERY_SOLICITATION';
export const INJECTION_SERVICE_FIND_BY_SURGERY_SOLICITATION =
  '@INJECTION_SERVICE_FIND_BY_SURGERY_SOLICITATION';
export const INJECTION_SERVICE_DELETE_SURGERY_SOLICITATION =
  '@INJECTION_SERVICE_DELETE_SURGERY_SOLICITATION';

// USE CASES
export const INJECTION_USECASE_CREATE_SURGERY_SOLICITATION =
  '@INJECTION_USECASE_CREATE_SURGERY_SOLICITATION';
export const INJECTION_USECASE_UPDATE_SURGERY_SOLICITATION =
  '@INJECTION_USECASE_UPDATE_SURGERY_SOLICITATION';
export const INJECTION_USECASE_DELETE_SURGERY_SOLICITATION =
  '@INJECTION_USECASE_DELETE_SURGERY_SOLICITATION';
export const INJECTION_USECASE_FIND_BY_SURGERY_SOLICITATION =
  '@INJECTION_USECASE_FIND_BY_SURGERY_SOLICITATION';
export const INJECTION_USECASE_FIND_ALL_SURGERY_SOLICITATION =
  '@INJECTION_USECASE_FIND_ALL_SURGERY_SOLICITATION';
